### ISSUE TITLE
dark mode search box: text not visible

### ISSUE THREAD

**Issue by glicht** [demisto/content-docs#34]
## Describe the problem
In Dark Mode the search box text is almost non-visible.

## Screenshots
In the screenshot I typed `test` in the search box:
![image](https://user-images.githubusercontent.com/1395797/71856886-1ae84200-30ee-11ea-814d-5e120a681d78.png)

## Environment
 - OS: [e.g. Windows]
 - Browser: chrome
 - Browser Version:

## Suggested fix
Change css so text in search bar with dark mode is visable

**Comment by sserrata** [comment]
The following CSS variables can be used to change the text color.

Example only:

```css
:root {
  --ifm-navbar-search-input-color: var(--ifm-color-gray-900);
  --ifm-navbar-search-placeholder-color: var(--ifm-color-gray-900);
}
```
