### ISSUE TITLE
Issue with "OTRS" in @site/docs/reference/integrations/otrs.md

### ISSUE THREAD

**Issue by saiiman** [demisto/content-docs#849]
## Describe the problem

* Page: [OTRS](https://xsoar.pan.dev/docs/reference/integrations/otrs)
* Source: https://github.com/demisto/content/blob/master//Packs/OTRS/Integrations/OTRS/README.md

While setting up the OTRS integration I encountered some problems. 
First of all, I did not find any information on how to name the corresponding OTRS web service. Unfortunately, the name is an important detail to establish a connection.
Second, I was not able to retrieve incidents (OTRS Integration - fetch Incidents) or use the `otrs-get-ticket` command with a given `ticket_number` after the prober setup. For the setup I used the OTRS web service template which is linked on the XSOAR documentation page. (https://gitlab.com/rhab/PyOTRS/raw/master/webservices_templates/GenericTicketConnectorREST.yml)

## Environment
- OTRS 6 (Znuny)

## Suggested fix

Please consider to update your documentation and give the user the hint to name the used OTRS web service as follows: `GenericTicketConnectorREST`. This information can also be checked in the XSOAR debug logs of any OTRS command.

I was able to fix the second problem by adding a new web service endpoint on OTRS side. I would recommend updating the given template or writing a note about the missing endpoint. Below you can find the corresponding update to the template.

```yml
---
Debugger:
  DebugThreshold: debug
  TestMode: '0'
Description: Ticket Connector REST
FrameworkVersion: 6.0.38
Provider:
  Operation:
    TicketSearchGET:
      Description: 'Search for Tickets by e.g. ticket_number or TicketCreateTimeNewerDate'
      IncludeTicketData: '0'
      Type: Ticket::TicketSearch
[...]
  Transport:
    Config:
      AdditionalHeaders: ~
      KeepAlive: ''
      MaxLength: '100000000'
      RouteOperationMapping
        TicketSearchGET:
          RequestMethod:
          - GET
          Route: /Ticket
[...]
```
